#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/email_scheduler_db
#spring.datasource.username=user
#spring.datasource.passwor=password
#
#spring.mail.protocol=smtp
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAIL_NAME}
#spring.mail.password=${MAIL_PASS}
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/email_scheduler_db
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: none

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_NAME}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true